### ISSUE TITLE
Versão Mobile da lista

### ISSUE THREAD

**Issue by nic** [graphql-brasil/empresas-que-usam-graphql-no-brasil#3]
Seguindo a ideia de https://github.com/react-brasil/empresas-que-usam-react-no-brasil/blob/master/MOBILE.md

Criar uma versão amigável para telas pequenas.

**Comment by nic** [comment]
@kwekwwelkwelk pode ajudar a gente aqui também?

**Comment by gabrielferreiraa** [comment]
PR colocando MOBILE.md -> https://github.com/graphql-brasil/empresas-que-usam-graphql-no-brasil/pull/4

Faltando alguns ajustes, mas o @kwekwwelkwelk criou a versão mobile pra gente! ❤️ 
Vou fechar a issue!
