### ISSUE TITLE
[DÚVIDAS] - Usecases com Graphql

### ISSUE THREAD

**Issue by GabrielFariasz** [graphql-brasil/empresas-que-usam-graphql-no-brasil#45]
Pessoal, boa tarde!

Não sei se a aba de issues é o melhor lugar para isso ( provavelmente não ), mas estou criando uma palestra com um colega de trabalho sobre graphql e gostaria de conversar com alguém que tenha um usecase real com o graphql.

Se você tem experiência e quiser colaborar com nossa palestra, seria massa bater um papo com você =)

meu e-mail, caso queiram entrar em contato: gabriel.farias3126@gmail.com

**Comment by nic** [comment]
Bom dia, Gabriel!
O melhor lugar para conseguir isso seria os slacks das comunidades GraphQL e React Brasil

GraphQL: https://graphql-slack.now.sh
React: https://react.now.sh

Abraço.
